### ISSUE TITLE
Changing the AgentPath variable

### ISSUE THREAD

**Issue by kubanjie** [ChrisLGardner/AzurePipelinesDeploymentGroups#14]
### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Public version in Azure DevOps, deploying to an on-premises Machine. 

### Expected behaviour and actual behaviour
Not able to change the path  the Deployment Agents are installed in. Changing the AgentPath variable doesn't seem to do anything and the task always defaults to C:\azagent; even if you set environment variables on the target machine or in the AddMachine.ps1. It'd be great to be able to expose this setting so it can be set as a variable in Azure DevOps. Otherwise works great and thanks. 

### Steps to reproduce the problem
Change the AgentPath variable in AddMachine.ps1 or set an env variable for SystemDrive on the target machine and deploy the task. It still defaults to C:\azagent no matter what SystemDrive is set to,

**Comment by ChrisLGardner** [comment]
That's something I really should have exposed from the start. I'll see if I can get that done in the next day or two for you.

**Comment by ChrisLGardner** [comment]
This should be in the latest release 0.1.35 in the next hour or so.
